Feature/error handling
uwcirg/AHRQ-CDS-Connect-PAIN-MANAGEMENT-SUMMARY pull request #83
Opened 2021-07-26 23:45 UTC by achen2401

2021-07-30 18:51 UTC, ivan-c requested changes
Looks good! One minor issue but ready to merge otherwise

2021-07-30 18:51 UTC, ivan-c commented on src/components/Landing.js
> +    const auditURL = `${getEnv("REACT_APP_EPIC_SUPPORTED_QUERIES")}/auditlog`;
The base URL of the confidential backend should be configured as `REACT_APP_CONF_API_URL`

```suggestion
    const auditURL = `${getEnv("REACT_APP_CONF_API_URL")}/auditlog`;
```

2021-08-16 18:31 UTC, pbugni approved these changes

2021-08-16 18:39 UTC, ivan-c approved these changes

2021-08-16 18:44 UTC, merged